version: '3.8'

services:
  movie_service:
    build: ./movie-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://movie_user:movie_password@movie_db:5432/movie_db
    depends_on:
      - movie_db

  cast_service:
    build: ./cast-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://cast_user:cast_password@cast_db:5432/cast_db
    depends_on:
      - cast_db

  movie_db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password

  cast_db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: cast_db
      POSTGRES_USER: cast_user
      POSTGRES_PASSWORD: cast_password
